language: go

dist: focal

go: "1.19.x"

notifications:
  email: true

env:
  global:
    - GO111MODULE=on

before_install:
  - sudo apt-get update
  - pyenv global 3.8

install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.62.0

script:
  - make travis-ci

before_deploy:
  - nvm install 18
  - npm install -g npm@9.x
  - npm install @semantic-release/changelog
  - npm install @semantic-release/exec
  - npm install @semantic-release/git
  - npm install @semantic-release/github
  - pip install --user bump2version

deploy:
  - provider: script
    script: npx semantic-release
    skip_cleanup: true
    on:
      go: '1.19.x'
      branch: main
